name: Build and Package

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-package-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out repository code

    - name: Install build tools and dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake make

    - name: Build the project (Ubuntu)
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Upload installer as artifact 
      uses: actions/upload-artifact@v2
      with:
        name: poker-eval-linux-amd64
        path: build/*



  build-and-package-arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install build tools and dependencies (ARM64)
      run: sudo apt-get update && sudo apt-get install -y cmake make gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

    - name: Build the project (ARM64)
      run: |
        mkdir build-arm64
        cd build-arm64
        cmake ..
        make

    - name: Upload installer as artifact 
      uses: actions/upload-artifact@v2
      with:
        name: poker-eval-linux-arm64
        path: build-arm64/*

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Install CMake
      run: choco install cmake -y

    - name: Install Visual Studio Build Tools
      run: choco install visualstudio2022buildtools -y --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

    - name: Configure and Build with CMake
      run: |
        mkdir build  
        cd build  
        cmake .. -G "Visual Studio 17 2022"  
        cmake --build .  

    - name: Upload installer as artifact (Windows)
      uses: actions/upload-artifact@v2
      with:
        name: poker-eval-windows-amd64
        path: build/Debug/*.*


  build-mac-os:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Setup environment
        run: |
          brew update
          brew install cmake
          brew install make

      - name: Build the project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Upload installer as artifact
        uses: actions/upload-artifact@v2
        with:
          name: poker-eval-darwin-amd64
          path: build/*