name: Build and Package

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-package-ubuntu:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Check out repository code

    - name: Install build tools and dependencies
      run: sudo apt-get update && sudo apt-get install -y cmake make

    - name: Build the project (Ubuntu)
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Prepare package files (Ubuntu)
      run: |
        mkdir -p package/DEBIAN
        echo "Package: libpoker-eval" > package/DEBIAN/control
        echo "Version: 140.0.0" >> package/DEBIAN/control
        echo "Architecture: amd64" >> package/DEBIAN/control
        echo "Description: Poker evaluation library" >> package/DEBIAN/control
        mkdir -p package/usr/lib
        cp build/libpoker_lib.so package/usr/lib/

    - name: Build .deb package (Ubuntu)
      run: dpkg-deb --build package

    - uses: actions/upload-artifact@v2
      with:
        name: libpoker-eval-amd64.deb
        path: package.deb

  build-and-package-arm64:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Install build tools and dependencies (ARM64)
      run: sudo apt-get update && sudo apt-get install -y cmake make gcc-aarch64-linux-gnu g++-aarch64-linux-gnu

    - name: Build the project (ARM64)
      run: |
        mkdir build-arm64
        cd build-arm64
        cmake -DCMAKE_TOOLCHAIN_FILE=../arm64-toolchain.cmake ..
        make

    - name: Prepare package files (ARM64)
      run: |
        mkdir -p package-arm64/DEBIAN
        echo "Package: libpoker-eval" > package-arm64/DEBIAN/control
        echo "Version: 140.0.0" >> package-arm64/DEBIAN/control
        echo "Architecture: arm64" >> package-arm64/DEBIAN/control
        echo "Description: Poker evaluation library" >> package-arm64/DEBIAN/control
        mkdir -p package-arm64/usr/lib
        cp build-arm64/libpoker_lib.so package-arm64/usr/lib/

    - name: Build .deb package (ARM64)
      run: dpkg-deb --build package-arm64

    - uses: actions/upload-artifact@v2
      with:
        name: libpoker-eval-arm64.deb
        path: package-arm64.deb

  build-windows:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout code

    - name: Install CMake
      run: choco install cmake -y

    - name: Install Visual Studio Build Tools
      run: choco install visualstudio2022buildtools -y --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64"

    - name: Configure and Build with CMake
      run: |
        mkdir build  
        cd build  
        cmake .. -G "Visual Studio 17 2022"  
        cmake --build .  

    - name: Create Installer with CPack
      run: |
        cd build
        cpack -G NSIS

  build-mac-os:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        name: Checkout code

      - name: Setup environment
        run: |
          brew update
          brew install cmake
          brew install make

      - name: Build the project
        run: |
          mkdir build
          cd build
          cmake ..
          make

      - name: Create PKG
        run: |
          mkdir pkgroot  
          cp -r build/. pkgroot/  
          pkgbuild --root pkgroot \
                   --identifier com.yourcompany.poker-eval \
                   --version "140.0.0" \
                   --install-location /Applications \
                   poker-eval.pkg

      - name: Upload PKG as artifact
        uses: actions/upload-artifact@v2
        with:
          name: poker-eval.pkg
          path: poker-eval.pkg